### ISSUE TITLE
Very pretty bad Readme

### ISSUE THREAD

**Issue by aahanaggarwal** [emwno/FQ#1]
Am I beautiful?

**Comment by emwno** [comment]
You are as beautiful to the world as a flower is to a garden. 
But the garden has better flowers.
So no.
Wah wah wah!

**Comment by aahanaggarwal** [comment]
👎 👎 👎 👎

**Comment by aahanaggarwal** [comment]
FuckFragment isn't the best name, is it?

**Comment by emwno** [comment]
Can you stop stalking me? thxfam

**Comment by aahanaggarwal** [comment]
What does this app do exactly? Please make the [readme](https://github.com/emwno/FQ/blob/master/README.md) slightly better.

**Comment by emwno** [comment]
Readme updated
